### ISSUE TITLE
Content [Catalyst TV]: Add new episodes to CatalystTV

### ISSUE THREAD

**Issue by PardusEidolon** [C3ETH/c3eth.github.io#171]
### Page Title

CatalystTV

### Description of change

As part of our Fund 6 proposal, Connecting Voters and Proposers @Mietran0407 is doing a CatalystTV series or 5-minute interviews with Catalyst Proposers. These videos interviews will be transcribed, translated, and embedded into our website.

I will upload the remaining episodes in english as a base for translation and to get things started.

### Is your suggestion and addition, or a change?

Change to exisitng page

### Which language does the change affect?

- [X] **English**
- [X] **Indonesian**
- [X] **Japanese**
- [X] **Korean**
- [X] **Vietnamese**

### Which section of the website should the change be made?

Other

### Website URL

https://easterntownhall.com/

### Source Document URL

https://easterntownhall.com/catalysttv/

### Additional Information

See @Mietran0407 Catalyst Fund 7 Proposal [Cardano Catalyst TV](https://cardano.ideascale.com/a/dtd/Cardano-Catalyst-TV/381619-48088).

More than 10 episodes have been uploaded but not added to the main website, new pages need to be created as well as a template for easy integration with the website.

**Comment by Mietran0407** [comment]
Here I will provide detailed information about those English videos and hope Jack will support me upload them on the web page. Thank youuuuu!

### Episode 1

Haskell Book Vietnamese/Japanese Translation - Quang Daniel

### Proposal details

**Challenge F8**: Developer Ecosystem
Haskell Book Japanese Translation
https://cardano.ideascale.com/c/idea/404202
Haskell Book Vietnamese Translation
https://cardano.ideascale.com/c/idea/403891

### Link Video

**Link drive**: https://drive.google.com/file/d/15Lfh9F001GtCG-X8nfgVdQ14sheeREAt/view?usp=sharing
**Link youtube**: https://www.youtube.com/watch?v=bDACvliqIPU&t=14s


### Description

**Proposer’s background:**

Mr. Curtis D'Alves: 
• 5 years of Haskell programming experience
• Haskell Programming Tutorial Youtube Channel:


Ms.Ha: Japanese interpreter, translator and blockchain project reviewer.
 

Mr. Quang Daniel: 
• 7 years experience as an English teacher and translator
• Telegram: [https://t.me/quangdaniel](https://www.youtube.com/redirect?event=video_description&redir_token=QUFFLUhqbGItRjE0NzBWdzRoV3h3R1AwVUViRUJGaVluUXxBQ3Jtc0ttMGhUbkhSVFdnNlY3N1YwZU84eXpOTFBSN1BiZ3pxNl9GSEJHdVpqYzBlTXpYMTBzYUE4eFJwQ1dGNG16V2ktb3VQclNOSm1XMXNLZ1NDc0pZNTIzRXhsMUktT2NrNmY1N2c5SExHZzZ5RFlFWENCdw&q=https%3A%2F%2Ft.me%2Fquangdaniel)

Ms. Hannah – Community Admin
• Founder of Vietnamese Cardano Community (helping 40k followers)
• One year of experience in operating a stake pool (SPO)
• Experience in blockchain financial research and investment since 2017
• Blockchain product and market research specialist
• Telegram: [https://t.me/hannahgates](https://www.youtube.com/redirect?event=video_description&redir_token=QUFFLUhqa1pqQ2pCNUNmUnA1QlU0Tm5JSkhvT1IxelN0d3xBQ3Jtc0ttY2ZlbUNHelZEN2VoSURpeUpuWmRub1RaZDJLZFhFcWV2Z2VNbUYzaWx6cERPMkI3YVB2anRhRlA0Yk11UG04NFpXZ3dXbDRTcFhONzNDbUxQRnpBRkpEQTRMSERXVFd3TVl0bGkzbnJDRWRJMmE3VQ&q=https%3A%2F%2Ft.me%2Fhannahgates)

 
 **Track the team activities:** 
[[https://www.youtube.com/watch?v=et1We...](https://www.youtube.com/watch?v=et1WeaZlQm0&t=0s)](https://www.youtube.com/watch?v=et1WeaZlQm0&t=0s)

Leave a comment on what you think of this proposal and give the team your vote!!!!

**Comment by Mietran0407** [comment]
### Episode 2

Haskell Course For Beginner/ Vietnamese  - Quang Daniel

### Proposal details

1. Challenge: F8: Developer Ecosystem
Proposal: Haskell Course For Beginner
https://cardano.ideascale.com/c/idea/399961

2. Challenge: F8: Scale-UP Cardano's Community Hubs
Proposal: Haskell Course for Vietnamese
https://cardano.ideascale.com/c/idea/399969

### Link Video

**Link drive**: https://drive.google.com/file/d/1z9HfD_PTNlWQdQLL3GXA0cPXxt1LT9Po/view?usp=sharing
**Link youtube**: https://www.youtube.com/watch?v=mWvgegef6yc


### Description

Stop by to give kudos to this wonderful proposal by Mr. Quang Daniel from Vietnam.

**Proposer’s background:**

Mr. Curtis D'Alves: 
• 5 years of Haskell programming experience
• Haskell Programming Tutorial Youtube Channel: 

Mr. Quang Daniel: 
• 7 years of experience as an English teacher and translator
• Telegram: [https://t.me/quangdaniel]

Ms. Hannah – Community Admin
• Founder of Vietnamese Cardano Community (helping 40k followers)
• One year of experience in operating a stake pool (SPO)
• Experience in blockchain financial research and investment since 2017
• Blockchain product and market research specialist
• Telegram: [https://t.me/hannahgates]
 
 **Track the team activities:** 
https://www.youtube.com/watch?v=et1WeaZlQm0&t=0s

**Comment by Mietran0407** [comment]
### Episode 3

Townhall Channel in Vietnamese - ELPI 

### Proposal details

F8: Scale-UP Cardano's Community Hubs
Proposal: Townhall Channel in Vietnamese
https://cardano.ideascale.com/c/idea/398044

### Link Video

**Link drive**: https://drive.google.com/file/d/1vwyJWOyhk4GJHMIOh50Ff6tCYVsV9Kou/view?usp=sharing
**Link youtube**: https://www.youtube.com/watch?v=NaHXYSriukw&t=14s


### Description

**Proposers' background**

1. Linh Pham

@linhcardano - Australia: Challenge Team member of Fund 7. Cloud computing, Digital Forensic and Cyber Security academic staff since 2004. Co-host for Eastern Town Hall - English/Vietnamese.
Telegram: t.me/Elpidanang


2. Tien Nguyen Anh @tienna,

Founder of the VILAI stake pool, computer science experts, working in the Cardano/Crypto space since 201
LinkedIn: [https://www.linkedin.com/in/tienna]
Twitter: [https://twitter.com/tiennganh]
Telegram: t.me/tiennguyenanh


3. Tan To Nguyen Duy @tantnd,

an experienced engineer in DevOps. Having worked in many technology conglomerates in Vietnam, startups also. Participating in building many software systems serving hundreds of thousands of users, such as Payments, Social Networking.
www: [https://tantnd.me
Twitter: [https://twitter.com/duytann_]
Telegram: t.me/tantnd
Github: [https://github.com/tanrobotix]


4. Mie Tran @mie.tran.0407

Vietnam: English and International Business major with experience working with western businesses and translation. Co-host for Cardano Eastern TownHall - English/Vietnamese.
Linked: [https://www.linkedin.com/in/ngocmytranle0407/]
Telegram: @mietran0407


5. Hieu Nguyen Van @nvhieu

Founder of HADA stake pool, member of Plutus Pioneer Program, Lead Technical Support at many successful startups.
Telegram: t.me/nvhieu1978
Linkedin: Linkedin: https://www.linkedin.com/in/nguyen-van-hieu-b4410121b

**Comment by Mietran0407** [comment]
### Episode 4

Challenge & Scouted for Students - Issa Ichikawa 

### Proposal details

Challenge: F8: Fund9 challenge setting
Proposal: Challenge & Scouted for Students
https://cardano.ideascale.com/c/idea/399737

### Link Video

**Link drive**: https://drive.google.com/file/d/1Jqp3z8xenq2UQFG1A0_dMWemvHWfEKDI/view?usp=sharing
**Link youtube**: https://www.youtube.com/watch?v=A44Dg2rvfyk&list=PLgIO96BXrRnb51UTv6rvDcOH6YebH8RAN&index=6


### Description

Please come and visit this meaningful idea for the challenge setting for Fund8

**Proposers' background**

・Issa Ichikawa (Twitter: [https://twitter.com/Cardano_ISSA]

- 21-year-old Junior at Waseda University in Japan
- Student entrepreneur
- Catalyst Fund6 raiser
- Catalyst CA
- Catalyst Fund6 Challenge Team Member (Connecting Japan Community)


・YUTA (Twitter: [https://twitter.com/yuta_cryptox]

- Cardano Ambassador
- SPO
- Japan representative of Eastern Town Hall Meeting
- Catalyst Fund2,6,7 raiser
- Catalyst CA
- Catalyst Fund6 Challenge Team Member (Connecting Japan Community)

**Comment by Mietran0407** [comment]
### Episode 5

Cardano Hub Indonesia-Video Series - Dion Setyotomo

### Proposal details

Challenge: F8: Scale-UP Cardano's Community Hubs
Cardano Hub Indonesia-Video Series Proposal 
https://cardano.ideascale.com/c/idea/401709

### Link Video

**Link drive**: https://drive.google.com/file/d/1iFaKBkRxpLF2it9C1mntUJkOxaL7YpfT/view?usp=sharing
**Link youtube**: https://www.youtube.com/watch?v=6gFEJ9eGzsY&list=PLgIO96BXrRnb51UTv6rvDcOH6YebH8RAN&index=7


### Description

Dion Setyotomo: 

- Project Manager, 
- Business Development
- Cardano Indonesia Community Manager
-  Eastern Hemisphere Town Hall member
- Discord admin for Cardano Indonesia Community

Linked: https://www.linkedin.com/in/dion-p-setyotomo-4ab6508

Andreas Sosilo:

- Software Developer
-  Cardano Foundation Ambassador for Indonesia
- Cardano Indonesia Community Manager
- Eastern Hemisphere Town Hall Team
Linked: https://www.linkedin.com/in/andreassosilo/

**Relevant connections and links**

- This proposal is in direct partnership with the Instagram influencer Cardano Indonesia, an Instagram influencer that focuses on discussing anything and everything Cardano has amassed a 1,000+ following. Their channel can be found at the following link: https://www.instagram.com/cardanoindonesia

- This proposal is supported by the two largest Indonesian SPO's ; SPO Kawanua (with 2,908 Tele members) and SPO Cardanesia (with 923 members) who will act as a source of content output reference and content distribution channel. Their channel can be found at the following links: https://t.me/KawanCardano & https://t.me/cardanesian

- This proposal is also supported by the Eastern Town Hall Indonesia community (with 299 Tele members and 160+ Discord members) who will act as a source of content output reference and content distribution channel. Their channel can be found in the following links: https://t.me/EHTIndonesia

**Also track for the team's activities:**

Cardano Hub Indonesia - Workshops: https://cardano.ideascale.com/a/dtd/Cardano-Hub-Indonesia-Workshops/380910-48088
DID for Cardano Indonesia Community: https://cardano.ideascale.com/a/dtd/DID-for-Cardano-Indonesia-Community/380911-48088
Community Web Portal in Bahasa: https://cardano.ideascale.com/c/idea/381632

**Comment by Mietran0407** [comment]
### Episode 6

Cardano SAY NO Plastic Straws | C4O - Trong Nguyen - Dang Nguyen

### Proposal details

F8: Miscellaneous Challenge
Cardano SAY NO Plastic Straws | C4O
https://cardano.ideascale.com/c/idea/398112

### Link Video

**Link drive**: https://drive.google.com/file/d/1PRE-4vIPmnBmvTpwXCetqNjUzyyF2tXy/view?usp=sharing
**Link youtube**: https://www.youtube.com/watch?v=hS1OK-i7SW8&t=4s

### Description

Too many animals &marine life are victimized and hurt by plastic straws. Does Cardano know that? How does Cardano act to solve this problem? We produce straws from natural grass to replace plastic straws. The goal of reducing waste is plastic straws into the environment and ocean.

We have members who have set up start-ups and are experts in IT and eco-friendly products. This project gives us a great motivation to work for a common global future.

- Trong: Project Founder with 15+ years of experience in information technology and start-ups, e-commerce, mobile content digital, a game studio, and environmentally friendly products. He will be in charge of materials, products and production processes, product packaging, and quality control.

(https://www.linkedin.com/in/trong-nguyen-4092b568/)

- Khanh: Over 15 years working in the Japanese market, in charge of import and export and product communication, He is a person who is especially interested in natural products introduced into daily life. In addition, he is an expert in the security of information technology systems at Fortinet.

(https://www.linkedin.com/in/khanh-pham-ngoc-79541371/)

- Tuan: In charge of e-commerce and community operations, He has been working for over 15 years in the software development industry and is the main engineer running the following ADA stake pool operator of Technotes Asia Pool.

(https://github.com/CWThun)

- Khoa: is an automation engineer, an activist for the marine environment in Asia. Since 2019, he has volunteered to conserve Sea Turtles in Hon Cau Island, Binh Thuan Vietnam, organized by IUCN and US FWS. With a mission to develop communities that protect marine species from human impact from plastic waste, he has the experience necessary for a successful project for the Cardano community.

(https://www.iucn.org/asia/countries/viet-nam/marine-turtle-conservation)

- HoangDang: has many years of experience in international trade and the export of goods.
Participating in the project with the role of developing brands and products for the global market.
He is active in the field of education and human resource development projects. He is also a lover of new technology and eco-friendly products made from nature.

 [hoangdang2208@hoangdang2208](https://cardano.ideascale.com/c/profile/3126638)

- ADABoys LAB: A group of technology experts, especially focusing on Cardano blockchain, will support ADA payment integration and interaction with e-commerce systems.

With the project that has been Funded 7 cPay - ADA payment on the COTI platform, ADAboys LAB team can fully integrate with shops and other e-commerce platforms.

https://mobile.twitter.com/boys_ada

- Technotes Asia Pool provides technical support and is an ADA pool operator for the Asia region.

https://www.technotes.asia/

We are also active on the Weforum forum for reducing waste and plastic straws in the ocean.
https://www.weforum.org/videos/the-ocean-will-have-4-times-more-plastic-trash-in-it-by-2050
